In [1]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
#train_df = pd.read_csv("datasets/tamil_offensive_full_train.csv")
#dev_df = pd.read_csv("datasets/tamil_offensive_full_dev.csv")
#test_df = pd.read_csv("datasets/tamil_offensive_full_test.csv")

In [3]:
import os

print(os.listdir("datasets"))

['tamil_offensive_full_dev.csv', 'tamil_offensive_full_test.csv', 'tamil_offensive_full_train.csv']

In [4]:
with open("datasets/tamil_offensive_full_train.csv", "r", encoding="utf-8") as f:
    for _ in range(10):
        print(repr(f.readline()))

'movie vara level la Erika poguthu\tNot_offensive\t\n'
'I love Ajith Kumar Vivegam movie inki mjy bht achi lgi\tnot-Tamil\t\n'
'Padam nalla comedy padama irukum polaye..\tNot_offensive\t\n'
'karthick subburaj anne .... intha padam vetri adaya unagalukku ennudaya valthukkal...\tNot_offensive\t\n'
'கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁\tNot_offensive\t\n'
'ippo intha trailer ah parkuravana oru like podunga\tNot_offensive\t\n'
'En thalaivan yogi babu irukkaar. Padam vera level laa irukkum\tNot_offensive\t\n'
'Nerkonda parvai...  Sema sema sema trailer\tNot_offensive\t\n'
'ஏய் இது 96 யார் ஏமாத்தறீங்க? செம பின்னிட்டீங்க\tNot_offensive\t\n'
'படம் கண்டிப்பாக வெற்றி பெற வேண்டும் செம்ம vara level\tNot_offensive\t\n'

In [5]:
train_df = pd.read_csv(
    "datasets/tamil_offensive_full_train.csv",
    sep="\t",
    header=None,
    names=["text", "label", "extra"]
)

dev_df = pd.read_csv(
    "datasets/tamil_offensive_full_dev.csv",
    sep="\t",
    header=None,
    names=["text", "label", "extra"]
)

test_df = pd.read_csv(
    "datasets/tamil_offensive_full_test.csv",
    sep="\t",
    header=None,
    names=["text", "label", "extra"]
)

In [6]:
train_df.head()

                                                text          label  extra
0                  movie vara level la Erika poguthu  Not_offensive    NaN
1  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil    NaN
2          Padam nalla comedy padama irukum polaye..  Not_offensive    NaN
3  karthick subburaj anne .... intha padam vetri ...  Not_offensive    NaN
4  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive    NaN

In [7]:
train_df.shape

(35139, 3)

In [8]:
train_df["label"].value_counts()

label
Not_offensive                           25425
Offensive_Untargetede                    2906
Offensive_Targeted_Insult_Group          2557
Offensive_Targeted_Insult_Individual     2343
not-Tamil                                1454
Offensive_Targeted_Insult_Other           454
Name: count, dtype: int64

In [9]:
train_df = train_df.drop(columns=["extra"])
dev_df = dev_df.drop(columns=["extra"])
test_df = test_df.drop(columns=["extra"])

In [10]:
train_df.head()

                                                text          label
0                  movie vara level la Erika poguthu  Not_offensive
1  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil
2          Padam nalla comedy padama irukum polaye..  Not_offensive
3  karthick subburaj anne .... intha padam vetri ...  Not_offensive
4  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive

In [11]:
X_train = train_df["text"]
y_train = train_df["label"]

X_dev = dev_df["text"]
y_dev = dev_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]

In [12]:
print(X_train.head())

0                    movie vara level la Erika poguthu
1    I love Ajith Kumar Vivegam movie inki mjy bht ...
2            Padam nalla comedy padama irukum polaye..
3    karthick subburaj anne .... intha padam vetri ...
4    கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁
Name: text, dtype: object

In [13]:
print(y_train.head())

0    Not_offensive
1        not-Tamil
2    Not_offensive
3    Not_offensive
4    Not_offensive
Name: label, dtype: object

In [14]:
vectorizer = TfidfVectorizer()

In [15]:
X_train_tfidf = vectorizer.fit_transform(X_train)

X_dev_tfidf = vectorizer.transform(X_dev)

X_test_tfidf = vectorizer.transform(X_test)

In [16]:
print(X_train_tfidf.shape)

(35139, 47693)

In [17]:
print(X_train_tfidf.shape)

(35139, 47693)

In [18]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [19]:
predictions = model.predict(X_dev_tfidf)

In [20]:
print("Accuracy:", accuracy_score(y_dev, predictions))
print()
print(classification_report(y_dev, predictions))

Accuracy: 0.7741567912488605

                                      precision    recall  f1-score   support

                       Not_offensive       0.80      0.97      0.88      3193
     Offensive_Targeted_Insult_Group       0.42      0.13      0.20       295
Offensive_Targeted_Insult_Individual       0.57      0.15      0.24       307
     Offensive_Targeted_Insult_Other       0.00      0.00      0.00        65
               Offensive_Untargetede       0.51      0.28      0.36       356
                           not-Tamil       0.89      0.62      0.73       172

                            accuracy                           0.77      4388
                           macro avg       0.53      0.36      0.40      4388
                        weighted avg       0.72      0.77      0.73      4388

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [21]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)
model.fit(X_train_tfidf, y_train)

predictions = model.predict(X_dev_tfidf)

print(classification_report(y_dev, predictions))

                                      precision    recall  f1-score   support

                       Not_offensive       0.94      0.69      0.79      3193
     Offensive_Targeted_Insult_Group       0.25      0.49      0.33       295
Offensive_Targeted_Insult_Individual       0.29      0.49      0.36       307
     Offensive_Targeted_Insult_Other       0.05      0.09      0.06        65
               Offensive_Untargetede       0.29      0.47      0.36       356
                           not-Tamil       0.63      0.85      0.73       172

                            accuracy                           0.64      4388
                           macro avg       0.41      0.51      0.44      4388
                        weighted avg       0.77      0.64      0.68      4388

In [22]:
# ==========================================
# Experiment 3 - Linear SVM
# ==========================================

from sklearn.svm import LinearSVC

svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

svm_predictions = svm_model.predict(X_dev_tfidf)

print("Accuracy:", accuracy_score(y_dev, svm_predictions))
print()
print(classification_report(y_dev, svm_predictions))

Accuracy: 0.773017319963537

                                      precision    recall  f1-score   support

                       Not_offensive       0.83      0.95      0.88      3193
     Offensive_Targeted_Insult_Group       0.39      0.21      0.27       295
Offensive_Targeted_Insult_Individual       0.43      0.23      0.30       307
     Offensive_Targeted_Insult_Other       0.00      0.00      0.00        65
               Offensive_Untargetede       0.42      0.32      0.36       356
                           not-Tamil       0.83      0.70      0.76       172

                            accuracy                           0.77      4388
                           macro avg       0.48      0.40      0.43      4388
                        weighted avg       0.73      0.77      0.74      4388

In [23]:
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)

X_dev_tfidf = vectorizer.transform(X_dev)

X_test_tfidf = vectorizer.transform(X_test)

In [24]:
# Experiment 4 - Character TF-IDF + Linear SVM

In [25]:
char_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3,5)
)

In [26]:
X_train_char = char_vectorizer.fit_transform(X_train)

X_dev_char = char_vectorizer.transform(X_dev)

X_test_char = char_vectorizer.transform(X_test)

In [27]:
print(X_train_char.shape)

(35139, 459648)

In [28]:
char_svm = LinearSVC(random_state=42)

char_svm.fit(X_train_char, y_train)

LinearSVC(random_state=42)

In [29]:
char_predictions = char_svm.predict(X_dev_char)

In [30]:
print(classification_report(y_dev, char_predictions))

                                      precision    recall  f1-score   support

                       Not_offensive       0.84      0.95      0.89      3193
     Offensive_Targeted_Insult_Group       0.46      0.25      0.33       295
Offensive_Targeted_Insult_Individual       0.53      0.30      0.38       307
     Offensive_Targeted_Insult_Other       0.00      0.00      0.00        65
               Offensive_Untargetede       0.43      0.33      0.37       356
                           not-Tamil       0.87      0.72      0.79       172

                            accuracy                           0.78      4388
                           macro avg       0.52      0.43      0.46      4388
                        weighted avg       0.74      0.78      0.76      4388

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [31]:
# Experiment 5 - Word + Character TF-IDF + Linear SVM

In [32]:
from scipy.sparse import hstack

In [33]:
X_train_combined = hstack([X_train_tfidf, X_train_char])

X_dev_combined = hstack([X_dev_tfidf, X_dev_char])

X_test_combined = hstack([X_test_tfidf, X_test_char])

In [34]:
print(X_train_combined.shape)

(35139, 507341)

In [35]:
combined_svm = LinearSVC(random_state=42)

combined_svm.fit(X_train_combined, y_train)

LinearSVC(random_state=42)

In [36]:
combined_predictions = combined_svm.predict(X_dev_combined)

In [37]:
print(classification_report(y_dev, combined_predictions))

                                      precision    recall  f1-score   support

                       Not_offensive       0.84      0.94      0.89      3193
     Offensive_Targeted_Insult_Group       0.39      0.24      0.30       295
Offensive_Targeted_Insult_Individual       0.44      0.26      0.33       307
     Offensive_Targeted_Insult_Other       0.00      0.00      0.00        65
               Offensive_Untargetede       0.41      0.36      0.38       356
                           not-Tamil       0.85      0.72      0.78       172

                            accuracy                           0.77      4388
                           macro avg       0.49      0.42      0.45      4388
                        weighted avg       0.74      0.77      0.75      4388

In [38]:
# Experiment 6 - Hyperparameter Tuning with GridSearchCV

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
param_grid = {
    "C": [0.1, 0.5, 1, 2, 5, 10]
}

In [41]:
grid = GridSearchCV(
    LinearSVC(random_state=42),
    param_grid,
    cv=5,
    scoring="f1_weighted",
    n_jobs=-1
)

In [42]:
grid.fit(X_train_char, y_train)

GridSearchCV(cv=5, estimator=LinearSVC(random_state=42), n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1, 2, 5, 10]}, scoring='f1_weighted')

In [43]:
print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'C': 2}
Best CV Score: 0.7448889333960851

In [44]:
best_model = grid.best_estimator_

grid_predictions = best_model.predict(X_dev_char)

print(classification_report(y_dev, grid_predictions))

                                      precision    recall  f1-score   support

                       Not_offensive       0.84      0.94      0.89      3193
     Offensive_Targeted_Insult_Group       0.42      0.27      0.33       295
Offensive_Targeted_Insult_Individual       0.44      0.30      0.35       307
     Offensive_Targeted_Insult_Other       0.00      0.00      0.00        65
               Offensive_Untargetede       0.42      0.34      0.37       356
                           not-Tamil       0.85      0.72      0.78       172

                            accuracy                           0.78      4388
                           macro avg       0.50      0.43      0.45      4388
                        weighted avg       0.74      0.78      0.75      4388

In [45]:
import os
import joblib

os.makedirs("models", exist_ok=True)

joblib.dump(best_model, "models/char_svm.pkl")
joblib.dump(char_vectorizer, "models/char_vectorizer.pkl")

print("Model saved successfully!")

Model saved successfully!